/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisView: typeof import('./src/views/AnalysisView.vue')['default']
    CheckingView: typeof import('./src/views/CheckingView.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    InventoryView: typeof import('./src/views/InventoryView.vue')['default']
    LoginView: typeof import('./src/views/LoginView.vue')['default']
    Monitor: typeof import('./src/views/Monitor/index.vue')['default']
    OrderView: typeof import('./src/views/OrderView.vue')['default']
    PayView: typeof import('./src/views/PayView/index.vue')['default']
    PresaleView: typeof import('./src/views/PresaleView.vue')['default']
    ProductView: typeof import('./src/views/ProductView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SalaryViews: typeof import('./src/views/SalaryViews.vue')['default']
    UserCreateView: typeof import('./src/views/UserCreateView.vue')['default']
    UserListView: typeof import('./src/views/UserListView.vue')['default']
    UserMapView: typeof import('./src/views/UserMapView.vue')['default']
  }
}
